db1:
  image: mysql:latest
  container_name: db1
  volumes:
    - C:/Users/henrique/Desktop/microservices/database/db1:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - 3306:3306
micsrv1:
  image: henriqueweiand/micsrv:1.1
  container_name: micsrv1
  restart: always
  volumes:
    - C:/Users/henrique/Desktop/microservices/service1:/var/www/html
  links:
    - db1:db1
  ports:
    - 80:80
app1:
  image: henriqueweiand/micsrv:1.1
  container_name: app1
  restart: always
  volumes:
    - C:/Users/henrique/Desktop/microservices/app1:/var/www/html
  links:
    - db1:db1
  ports:
    - 80:80
